// This file is used to generate the macro defines as needed
// on a system that does not have libcwd installed at all.
//
// It works as follows:
// In phase 1, all macros that are generated without libcwd
// are detected and written as an `undef' to "phase1.h".
// In phase 2, all extra macros as generated by libcwd with
// DEBUG and DEBUGMALLOC undefined are generated and written
// to nodebug.h.
//
// g++ -dM -E macrotest.cc | sed -e 's/#define \([^ ]*\).*/#undef \1/' > phase1.h
// g++ -dM -E -DPHASE2 macrotest.cc | egrep -v '(#define __|_H *$)' | sort > nodebug.h
//

#undef DEBUG
#undef CWDEBUG
#ifdef PHASE2
#include <libcw/debug_config.h>
#undef DEBUGMALLOC
#undef DEBUGMAGICMALLOC
#define LIBCW_SYS_H
#include <libcw/debug.h>
#include "phase1.h"
#undef PHASE2
#endif
