// This file is used to generate the macro defines as needed
// on a system that does not have libcwd installed at all.
//
// It works as follows:
// In phase 1, all macros that are generated without libcwd
// are detected and written as an `undef' to "phase1.h".
// In phase 2, all extra macros as generated by libcwd with
// CWDEBUG and DEBUGMALLOC undefined are generated and written
// to nodebug.h.  Macros starting with two underscores, ending
// in _H or containing the string DEBUG are not stored however:
// these are internal to libcwd and shouldn't be used by the
// user.
//
// g++ -dM -E $(CPPFLAGS) macrotest.cc | sed -e 's/#define \([^ ]*\).*/#undef \1/' > phase1.h
// g++ -dM -E $(CPPFLAGS) -DPHASE2 macrotest.cc 2>/dev/null | egrep -v '(#define __|_H *$|DEBUG)' | sort > nodebug.h
//

#undef DEBUG
#undef CWDEBUG
#ifdef PHASE2
#include <libcw/debug_config.h>
#undef DEBUGMALLOC
#undef DEBUGMAGICMALLOC
#define LIBCW_DEBUG_SYSD_H
#define LIBCW_GENERATION_OF_NODEBUG_H
#include <libcw/debug.h>
#include "phase1.h"
#undef PHASE2
#endif
