global srcdir subdir
global SHAREDLIBS STATICLIBS

catch "glob -nocomplain $srcdir/$subdir/*.cc" srcfiles
# set srcfiles $srcdir/$subdir/dlopen.cc
verbose "srcfiles are $srcfiles"

set prefix ""
foreach x $srcfiles {
    regsub "\\.cc$" $x "" prefix
    set bname [file tail $prefix]
    set args ""
    if [file exists ${prefix}.arg] {
      set id [open "${prefix}.arg" r];
      set args [read -nonewline $id];
      close $id;
    }
    set resfile "${prefix}.re"
    set options "regexp_match"

    if [file exists ${prefix}.inp] {
        set inpfile ${prefix}.inp
    } else {
        set inpfile ""
    }
    verbose "inpfile is $inpfile"

    if { $SHAREDLIBS != "" } {
      test_libcwd $options "${prefix}.cc" "" $inpfile $resfile $args
    }
    if { $STATICLIBS != "" } {
      test_libcwd "static $options" "${prefix}.cc" "" $inpfile $resfile $args
    }
}
