# The directory where the base Makefile resides:
BASEDIR=../../..

# List of subdirectories:
SUBDIRS=

# List source files:
CXXSRC:=$(shell find . -maxdepth 1 -mindepth 1 -type f ! -name perf.cc -name '*$(CPPEXT)' -printf '%f\n')

#-----------------------------------------------------------------------------

include $(PROTODIR)/sub/PTMakefile

#build::
#clean::
#depend::
